# Generated by Django 3.0.9 on 2023-03-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('author', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=128)),
                ('genre1', models.CharField(max_length=50)),
                ('genre2', models.CharField(max_length=50)),
                ('genre3', models.CharField(max_length=50)),
                ('trope1', models.CharField(max_length=50)),
                ('trope2', models.CharField(max_length=50)),
                ('trope3', models.CharField(max_length=50)),
            ],
        ),
    ]
