# Generated by Django 3.0.9 on 2023-03-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80)),
                ('feeback', models.CharField(max_length=400)),
            ],
        ),
    ]
