# Generated by Django 3.0.9 on 2023-05-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230501_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.CharField(default='NULL', max_length=80),
        ),
    ]
